config/routes.rb
Rails.application.routes.draw do

  resources :carts, only: [:index]
  post '/charges', controller: :carts, action: :create

  post '/checkout', controller: :carts, action: :checkout

  resources :restaurants, only: [:index, :new, :create, :show, :edit, :update]

  resources :dishes, only: [:new, :show, :create, :edit, :update] do
    post 'add_item', controller: :carts, action: :add_item
  end

  devise_for :users, controllers: { registrations: 'registrations'}

  resources :menus, only: [:index, :create, :new, :show, :edit, :update]

  root to: 'restaurants#index'

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :restaurants, only: [:index, :show]
      mount_devise_token_auth_for 'User', at: 'auth', controllers: { sessions: 'api/v1/login'}, skip: [:omniauth_callbacks]
      resources :carts, only: [:create]
    end
  end
end

app/models/menu.rb
class Menu < ApplicationRecord
  validates_presence_of :title
  validates_presence_of :restaurant

  has_and_belongs_to_many :dishes
  belongs_to :restaurant

end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  before_action :find_menu_from_params, only: [:show, :edit, :update]
  before_action :owner_has_restaurant?, only: :new

  load_and_authorize_resource

  def index
  end

  def new
    @menu = Menu.new
    @dishes = current_user.restaurant.dishes
  end

  def show
    @dishes = @menu.dishes.group_by(&:category)
  end

  def create
    restaurant = Restaurant.find_by(user: current_user)
    @menu = restaurant.menus.new(menu_params)
    if @menu.save
      flash[:notice] = 'Successfully added menu'
      render :show
    else
      flash[:alert] = @menu.errors.full_messages.first
      render :new
    end
  end

  def edit
    @dishes = current_user.restaurant.dishes
  end

  def update
    @menu.update(menu_params)
    render :show
  end

  private
  def menu_params
    params.require(:menu).permit(:title, {dish_ids: []})
  end

  def find_menu_from_params
    @menu = Menu.find(params[:id])
  end
end

app/views/menus/_form.html.haml
= form_for @menu, class: 'form-group' do |f|
  = f.label :title do
    = f.text_field :title, id: 'title', class: 'form-control'
  %p#dishes
    - unless current_user.restaurant.dishes.empty?
      %h3 Check to add dishes to menu:
      = f.collection_check_boxes :dish_ids, @dishes, :id, :name do |b|
        .checkbox
          = b.check_box + b.label
  - if current_page?(new_menu_path)
    = f.submit 'Create', id: 'create', class: 'btn btn-warning'
  - else
    = f.submit 'Update', id: 'update', class: 'btn btn-warning'

app/views/menus/edit.html.haml
.h1-top
  %h1 Edit menu: #{@menu.title}
.container
  .row
    .col-md-8.col-xs-12
      = render partial: 'form'

app/views/menus/index.html.haml
.row
  .column-md-12
    %h1 Menu for X
    %p Dish 1

app/views/menus/new.html.haml
.h1-top
  %h1 Add menu
.container
  .row
    .col-md-8.col-xs-12
      = render partial: 'form'

app/views/menus/show.html.haml
.h1-top
  %h1
    = @menu.title
.container
  .row
    .col-md-8.col-xs-12
      %br/
      - if current_user == @menu.restaurant.user #this is throwing a nil error
        = link_to 'Edit Menu', edit_menu_path(@menu)
      - if !@menu.dishes.nil?
        Dishes:
        %br/
        - @menu.dishes.each do |dish|
          = link_to dish.name, dish
          %br/