config/routes.rb
Rails.application.routes.draw do

  resources :carts, only: [:index]
  post '/charges', controller: :carts, action: :create

  post '/checkout', controller: :carts, action: :checkout

  resources :restaurants, only: [:index, :new, :create, :show, :edit, :update]

  resources :dishes, only: [:new, :show, :create, :edit, :update] do
    post 'add_item', controller: :carts, action: :add_item
  end

  devise_for :users, controllers: { registrations: 'registrations'}

  resources :menus, only: [:index, :create, :new, :show, :edit, :update]

  root to: 'restaurants#index'

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :restaurants, only: [:index, :show]
      mount_devise_token_auth_for 'User', at: 'auth', controllers: { sessions: 'api/v1/login'}, skip: [:omniauth_callbacks]
      resources :carts, only: [:create]
    end
  end
end

app/models/dish.rb
class Dish < ApplicationRecord
  PERMITTED_DISH_CATEGORIES = %w(Starters Mains Desserts)

  validates_presence_of :name
  validates_presence_of :description
  validates_presence_of :price
  validates_presence_of :restaurant
  validates_presence_of :category


  has_and_belongs_to_many :menus
  belongs_to :restaurant

  has_attached_file :image,
                    styles: { medium: '300x300>', thumb: '100x100>' },
                    default_url: 'assets/images/:style/missing.png'
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  before_action :find_dish_from_params, only: [:show, :edit, :update]

  load_and_authorize_resource
  before_action :owner_has_restaurant?, only: :new

  def new
    @dish = Dish.new
    @menus = Menu.where(restaurant: current_user.restaurant)
  end

  def create
    @dish = current_user.restaurant.dishes.create(dish_params)
    if @dish.save
      render :show
    else
      flash[:alert] = @dish.errors.full_messages.first
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @dish.update(dish_params)
      render :show
    else
      flash[:alert] = @dish.errors.full_messages.first
      render :edit
    end
  end

  private

  def dish_params
    params.require(:dish).permit(:name,
                                 :description,
                                 :price,
                                 :allergies,
                                 :ingredients,
                                 :calories,
                                 :category,
                                 {menu_ids: []},
                                 :highlight,
                                 :image)
  end

  def find_dish_from_params
    @dish = Dish.find(params[:id])
  end
end

app/views/dishes/_form.html.haml
= form_for @dish, html: {multipart: true, class: 'form-group'} do |form|
  = form.label :name, 'Dish Name'
  = form.text_field :name, class: 'form-control'
  = form.label :description, 'Dish description'
  = form.text_area :description, class: 'form-control'
  = form.label :category
  = form.select :category, options_for_select(Dish::PERMITTED_DISH_CATEGORIES), class: 'form-control'
  = form.label :price, 'Price'
  = form.text_field :price, class: 'form-control'
  = form.label :allergies, 'Allergy Info'
  = form.text_area :allergies, class: 'form-control'
  = form.label :calories, 'Calories'
  = form.text_field :calories, class: 'form-control'
  = form.label :ingredients, 'Ingredients'
  = form.text_field :ingredients, class: 'form-control'
  -# - if @dish.image?
  -#   = image_tag @dish.image.url
  -# - else
  -#   = image_tag '', id: 'preview', style: 'min-width: 130px; min-height: 130px;', onChange: 'readAndPreviewImage(this);'
  %p
    = form.label :image, 'Upload an image'
    = form.file_field :image
  %p.form-group
    = form.label :highlight
    = form.check_box :highlight

  %p#menus
    - if !@menus.nil?
      %h3 Add to Menu
      = form.collection_check_boxes :menu_ids, @menus, :id, :title do |b|
        .checkbox
          = b.check_box + b.label
  %p
    = form.submit 'Submit', class: 'btn btn-warning'

-# :javascript
-#   function readAndPreviewImage(input) {
-#     if (input.files && input.files[0]) {
-#       var reader = new FileReader();
-#       reader.onload = function (e) {
-#         $('#preview')
-#           .fadeIn("slow")
-#           .attr('src', e.target.result);
-#       };
-#       reader.readAsDataURL(input.files[0]);
-#     }
-#   }

app/views/dishes/edit.html.haml
.h1-top
  %h1 Edit dish
.container
  .row
    .col-md-8.col-xs-12
      = render partial: 'form'

app/views/dishes/new.html.haml
.h1-top
  %h1 Add a Dish
.container
  .row
    .col-md-8.col-xs-12
      = render partial: 'form'

app/views/dishes/show.html.haml
.h1-top
  %h1
    = @dish.name
.container
  .row
    .col-md-6
      %p
        %strong Category: #{@dish.category}
      %p Dish description: #{@dish.description}
      %p Dish price: #{@dish.price}
      %p Allergens: #{@dish.allergies}
      %p Ingredients: #{@dish.ingredients}
      %p Calories: #{@dish.calories}

      %p Menu(s):
      - @dish.menus.each do |menu|
        %p
          %strong= menu.title
        %br/
      - unless cannot? :create, ShoppingCart
        = link_to 'Add to cart', dish_add_item_path(@dish), method: :post, class: 'btn btn-success'
      - if can? :manage, @dish
        = link_to 'Edit dish', edit_dish_path(@dish), class: 'btn btn-primary'
    .col-md-6
      - unless @dish.image_file_name.nil?
        .dish_image
          = image_tag @dish.image.url(:medium)