config/routes.rb
Rails.application.routes.draw do

  resources :carts, only: [:index]
  post '/charges', controller: :carts, action: :create

  post '/checkout', controller: :carts, action: :checkout

  resources :restaurants, only: [:index, :new, :create, :show, :edit, :update]

  resources :dishes, only: [:new, :show, :create, :edit, :update] do
    post 'add_item', controller: :carts, action: :add_item
  end

  devise_for :users, controllers: { registrations: 'registrations'}

  resources :menus, only: [:index, :create, :new, :show, :edit, :update]

  root to: 'restaurants#index'

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :restaurants, only: [:index, :show]
      mount_devise_token_auth_for 'User', at: 'auth', controllers: { sessions: 'api/v1/login'}, skip: [:omniauth_callbacks]
      resources :carts, only: [:create]
    end
  end
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord

  PERMITTED_CATEGORIES = %w(Other Pizza Sushi Italian Thai Fast\ Food BBQ French Traditional Vegan Seafood TexMex)

  belongs_to :user
  has_many :menus, dependent: :destroy
  has_many :dishes, dependent: :destroy
  geocoded_by :full_address
  after_validation :geocode
  validates_presence_of :user, :name, :category, :street, :zipcode, :town
  validates :category, inclusion: { in: PERMITTED_CATEGORIES,
                                    message: '%{value} is not permitted'}


  def full_address
    [street, zipcode, town].join(', ')
  end

  def has_menus?
    self.menus != nil && self.menus.ids != nil
  end
end

app/controllers/api/v1/restaurants_controller.rb
class Api::V1::RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  load_and_authorize_resource except: :dropdown # potentially refactor this into ApplicationController
  before_action :check_for_exisiting_restaurant, only: [:new]
  before_action :find_restaurant_from_params, only: [:show, :edit, :update]

  def index
    @restaurants = Restaurant.all
    gon.all_restaurants = @restaurants
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params.merge({user: current_user}))
    if @restaurant.save
      render :show
    else
      flash[:alert] = @restaurant.errors.full_messages.first
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @restaurant.update_attributes(restaurant_params)
      render :show
    else
      flash[:alert] = @restaurant.errors.full_messages.first
      @restaurant.reload
      render :edit
    end
  end

  private

  def check_for_exisiting_restaurant
    unless current_user.restaurant.nil?
      flash[:alert] = 'You already have a restaurant, how many do you need?'
      redirect_back(fallback_location: root_path)
    end
  end

  def find_restaurant_from_params
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name,
                                       :category,
                                       :description,
                                       :street,
                                       :zipcode,
                                       :town)
  end
end

app/helpers/restaurant_helper.rb
module RestaurantHelper
  def dropdown_options
    Restaurant::PERMITTED_CATEGORIES.dup.insert(0, 'All Restaurants')
  end
end

app/views/restaurants/_form.html.haml
= form_for @restaurant, class: 'form-group'  do |f|
  = f.label :name
  = f.text_field :name, class: 'form-control', value: @restaurant.name
  = f.label :description
  = f.text_area :description, class: 'form-control', value: @restaurant.description
  = f.label :category
  = f.select :category, options_for_select(Restaurant::PERMITTED_CATEGORIES), {}, {class: 'form-control'}
  = f.label :street
  = f.text_field :street, class: 'form-control', value: @restaurant.street
  = f.label :zipcode
  = f.text_field :zipcode, class: 'form-control', value: @restaurant.zipcode
  = f.label :town
  = f.text_field :town, class: 'form-control', value: @restaurant.town
  %br/
  = f.submit 'Submit', class: 'btn btn-warning'

app/views/restaurants/edit.html.haml
.h1-top
  %h1 Edit restaurant: #{@restaurant.name}
.container
  .row
    .col-md-8.col-xs-12
      = render partial: 'form'

app/views/restaurants/index.html.haml
.question-row
  .question-container
    %h2 What do you feel like tonight?
    = render partial: 'category_drop'
#map{data: {test: {env: "#{Rails.env.test?}"}}}
%section#story.description_content
  .container
    .col-md-6
      %h1 About us
      %p.desc-text Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
    .col-md-6
      %h1 Popular restaurants
      - @restaurants.each do | restaurant |
        %ul
          %li
            = link_to restaurant.name, restaurant_path(restaurant.id)
%section#info.description_content
  .info.background_content
    %h1
      %span Quick
      deliveries

app/views/restaurants/new.html.haml
.h1-top
  %h1 New restaurant form
.container
  .row
    .col-md-8.col-xs-12
    = render partial: 'form'

app/views/restaurants/show.html.haml
.h1-top
  %h1
    = @restaurant.name
.container
  .row
    .col-md-8.col-xs-12
      %br/
      %br/
      = @restaurant.name
      %br/
      = @restaurant.category
      %br/
      = @restaurant.description
      %br/
      = @restaurant.street
      %br/
      = @restaurant.zipcode
      %br/
      = @restaurant.town
      %br/
      %br/

      %p
        - @restaurant.menus.each do |menu|
          = link_to menu.title, menu_path(menu)

      = link_to 'Edit', edit_restaurant_path(@restaurant), class: "btn btn-success"

  .highlighted
    %h3 Highlighted Dishes
    - @restaurant.dishes.where(highlight: true).limit(6).each do |dish|
      .col-sm-4
        .graybackground
          .dish.h4
            = dish.name
          .dish
            = dish.description
          .dish
            Price:
            = dish.price
          - unless dish.image.nil?
            .dish.image
              = image_tag dish.image.url(:medium)
          .order_button
            - if can? :create, ShoppingCart
              = link_to 'Add to cart', dish_add_item_path(dish), method: :post, class: 'btn btn-success'